### ISSUE TITLE
ValueError: could not broadcast input array from shape (144,192,256,1) into shape (144,192,256)

### ISSUE THREAD

**Issue by songwaimai** [arnab39/FewShot_GAN-Unet3D#15]
Hi, I have covert .img to .nii, but when i run python main.py(bad gan), the error is 
  File "E:\/slycode\FewShot_GAN-Unet3D-master\preprocess\preprocess.py", line 305, in __init__
    patch_shape,number_images_training)
  File "E:\/slycode\FewShot_GAN-Unet3D-master\preprocess\preprocess.py", line 162, in preprocess_dynamic_lab
    T1_vols[(case_idx-c-1), :, :, :] = read_vol(case_idx, 'T1', dir)
ValueError: could not broadcast input array from shape (144,192,256,1) into shape (144,192,256)
  should i change the (144,192,256) in the preprocess.py to (144,192,256,1)???

**Comment by songwaimai** [comment]
the problem has been resolved.

**Comment by TaoZhong11** [comment]
> the problem has been resolved.

Hi, how do you fix it?

**Comment by hkthirano** [comment]
@songwaimai 
Hi, how do you fix it?
